[package]
name = "hv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libax = { path = "../ulib/libax" }
page_table_entry = { path = "../../arceos/crates/page_table_entry" }
