[package]
name = "hypercraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"

[target.'cfg(target_arch = "riscv")'.dependencies]
riscv = "0.10.1"
