[package]
name = "hypercraft"
version = "0.1.0"
edition = "2021"
authors = ["KuangjuX <kuangjux@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
log = "0.4.17"
memoffset = { version = ">=0.6.5", features = ["unstable_const"] }
arrayvec = { version = "0.7.2", default-features = false }
spin = { version = "0.9", features = ["once", "rwlock", "spin_mutex"] }
tock-registers = "0.8.1"

cortex-a = "8.1.1"
aarch64-cpu = "9.3"

# arceos crates
page_table = { path = "../page_table" }
page_table_entry = { path = "../page_table_entry" }
arm_gic = { path = "../arm_gic" }
spinlock = { path = "../spinlock" }

memory_addr = { path = "../memory_addr" }
vm_config = { path = "../vm_config" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
riscv-decode = { git = "https://github.com/KuangjuX/riscv-decode.git" }
sbi-spec = { version = "0.0.6", features = ["legacy"] }
sbi-rt = {version = "0.0.2", features = ["integer-impls", "legacy"]}

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "11.0"
bitflags = "1.3"
bit_field = "0.10"
bit-set = { version = "0.5", default-features = false }
x86 = "0.52"
x86_64 = "0.14"
numeric-enum-macro = "0.2"