[package]
name = "driver_cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dtb = {path = "../../crates/dtb"}
arrayvec = { version = "0.7.2", default-features = false }
